version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OSM_DATA_PATH=/data/campus.osm.pbf
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
    volumes:
      - ./data:/data
      - ./app:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0 --save 60 1 --loglevel warning
    ports:
      - "127.0.0.1:6379:6379" # Bind Redis to localhost for security
    volumes:
      - redis_data:/data

volumes:
  redis_data:
